MonzaBundle\Entity\marque:
    type: entity
    table: null
    repositoryClass: MonzaBundle\Repository\marqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marque:
            type: string
            length: 255
        modele:
            type: string
            length: 255
        title:
            type: string
            length: 255
        puissance:
            type: string
            length: 255
        video:
            type: string
            length: 255
        histoire:
            type: string
            length: 255
    lifecycleCallbacks: {  }
