<?php

namespace MonzaBundle\Repository;

/**
 * circuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class circuitRepository extends \Doctrine\ORM\EntityRepository
{
}
