<?php

namespace MonzaBundle\Repository;

/**
 * tuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
