# Route pour la home
monza_homepage:
    path:     /
    defaults: { _controller: MonzaBundle:Default:index }

# Route pour la fiche description de chaque voiture
voiures_global:
    path:     /brands/{brandId}
    defaults: { _controller: MonzaBundle:Voiture:brand}

# Route pour toutes les voitures
voiures_globalB:
    path:     /brands
    defaults: { _controller: MonzaBundle:Voiture:brands }

# Route pour la fiche description de chaque circuit

monza_Circuits:
    path:     /circuits/{circuitId}
    defaults: { _controller: MonzaBundle:Circuits:circuit }

# Route pour tous les circuit
monza_globalC:
    path:     /circuits
    defaults: { _controller: MonzaBundle:Circuits:circuits }

# Routes pour la page USER
monza_inscription:
    path:     /inscription
    defaults: { _controller: MonzaBundle:User:Inscription }

monza_connection:
    path:     /connection
    defaults: { _controller: MonzaBundle:User:Connection }

monza_Qsn:
    path:     /qsn
    defaults: { _controller: MonzaBundle:Qsn:qsn }